services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=bank'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=secret'
#    healthcheck:
#      test: [ "CMD", "pg_isready" ]
#      interval: 3s
#      timeout: 5s
#      retries: 5
    ports:
      - '5000:5432'
#    labels:
#      org.springframework.boot.readiness-check.tcp.disable: false