server:
  port: 8081

spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: bank-race-condition-sb3
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always